
-- 1. 키워드 타입을 위한 ENUM 생성 ('latest', 'evergreen')
CREATE TYPE public.keyword_type AS ENUM ('latest', 'evergreen');

-- 2. 키워드를 저장할 'keywords' 테이블 생성
CREATE TABLE public.keywords (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    keyword_text TEXT NOT NULL UNIQUE,
    type public.keyword_type NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.keywords IS '콘텐츠 생성을 위한 키워드를 저장합니다.';
COMMENT ON COLUMN public.keywords.keyword_text IS '키워드 텍스트 (예: "건강한 아침 식단")';
COMMENT ON COLUMN public.keywords.type IS '키워드 종류: latest (최신) 또는 evergreen (평생)';
COMMENT ON COLUMN public.keywords.category IS '키워드 카테고리 (예: "건강", "IT")';

-- 3. 사용자별 키워드 사용 이력을 추적할 'user_used_keywords' 테이블 생성
CREATE TABLE public.user_used_keywords (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    keyword_id UUID NOT NULL REFERENCES public.keywords(id) ON DELETE CASCADE,
    used_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT user_used_keywords_user_id_keyword_id_key UNIQUE (user_id, keyword_id)
);

COMMENT ON TABLE public.user_used_keywords IS '어떤 사용자가 어떤 키워드를 사용했는지 추적합니다.';
COMMENT ON COLUMN public.user_used_keywords.user_id IS '사용한 사용자의 프로필 ID';
COMMENT ON COLUMN public.user_used_keywords.keyword_id IS '사용한 키워드의 ID';
COMMENT ON CONSTRAINT user_used_keywords_user_id_keyword_id_key ON public.user_used_keywords IS '사용자별로 동일한 키워드가 중복 사용되지 않도록 보장합니다.';

-- 4. 'user_used_keywords' 테이블에 Row Level Security (RLS) 활성화
ALTER TABLE public.user_used_keywords ENABLE ROW LEVEL SECURITY;

-- 5. 'user_used_keywords' 테이블에 대한 RLS 정책 생성
-- 사용자는 자신의 사용 이력만 보거나, 추가하거나, 삭제(초기화용)할 수 있습니다.
CREATE POLICY "Users can manage their own used keywords"
ON public.user_used_keywords FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 6. 'keywords' 테이블은 모든 로그인 사용자가 읽을 수 있도록 설정
ALTER TABLE public.keywords ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can read keywords"
ON public.keywords FOR SELECT
USING (auth.role() = 'authenticated');

-- 7. '평생 키워드' 데이터 채우기
INSERT INTO public.keywords (keyword_text, type, category) VALUES
('초보자용 주식 투자', 'evergreen', '금융'),
('ETF 투자 방법', 'evergreen', '금융'),
('파이썬 독학', 'evergreen', 'IT/기술'),
('리액트 상태 관리', 'evergreen', 'IT/기술'),
('클린 코드 작성법', 'evergreen', 'IT/기술'),
('일본 자유여행 코스', 'evergreen', '여행'),
('유럽 배낭여행 준비물', 'evergreen', '여행'),
('제주도 2박 3일', 'evergreen', '여행'),
('건강한 아침 식단', 'evergreen', '건강/요리'),
('에어프라이어 레시피', 'evergreen', '건강/요리'),
('홈트레이닝 루틴', 'evergreen', '건강/요리'),
('스트레스 해소법', 'evergreen', '자기계발'),
('효과적인 시간 관리', 'evergreen', '자기계발'),
('미라클 모닝 실천', 'evergreen', '자기계발'),
('가성비 좋은 노트북 추천', 'evergreen', 'IT/기술'),
('MBTI 유형별 특징', 'evergreen', '심리/라이프'),
('반려동물과 교감하는 법', 'evergreen', '심리/라이프');

-- 8. '최신 이슈' 예시 데이터 채우기 (이후 동적 시스템으로 대체 예정)
INSERT INTO public.keywords (keyword_text, type, category) VALUES
('2025년 여름 패션', 'latest', '패션'),
('최신 스마트폰 비교', 'latest', 'IT/기술'),
('AI 그림 그리기', 'latest', 'IT/기술'),
('국내 여행지 추천', 'latest', '여행');
