
-- 추가 평생 키워드 데이터 (약 138개)
INSERT INTO public.keywords (keyword_text, type, category) VALUES
-- 금융 & 투자
('CMA 통장 완벽 정리', 'evergreen', '금융'),
('주택청약 종합저축 1순위 조건', 'evergreen', '금융'),
('ETF QQQ 완벽 분석', 'evergreen', '금융'),
('S&P 500 투자 방법', 'evergreen', '금융'),
('달러 투자 하는 법', 'evergreen', '금융'),
('금 투자 방법', 'evergreen', '금융'),
('신용카드 혜택 비교', 'evergreen', '금융'),
('자동차 보험료 줄이는 팁', 'evergreen', '금융'),
('연말정산 환급금 많이 받는 법', 'evergreen', '금융'),
('사회초년생 1억 모으기', 'evergreen', '금융'),
('경제적 자유를 위한 파이프라인', 'evergreen', '금융'),
('디지털 노마드 세금 문제', 'evergreen', '금융'),
('가상화폐 투자 초보 가이드', 'evergreen', '금융'),
('부동산 경매 초보 가이드', 'evergreen', '금융'),
('P2P 투자 장단점', 'evergreen', '금융'),
('주식 MTS 사용법 비교', 'evergreen', '금융'),
('절세 상품 총정리 (IRP, ISA)', 'evergreen', '금융'),
('미국 배당주 포트폴리오', 'evergreen', '금융'),
('부동산 소액 투자 방법', 'evergreen', '금융'),
('핀테크 서비스 비교 분석', 'evergreen', '금융'),
('가계부 잘 쓰는 법', 'evergreen', '금융'),
('짠테크 노하우', 'evergreen', '금융'),

-- IT & 기술
('가성비 태블릿 추천', 'evergreen', 'IT/기술'),
('업무용 노트북 추천', 'evergreen', 'IT/기술'),
('VSCode 단축키 모음', 'evergreen', 'IT/기술'),
('파이썬으로 데이터 분석하기', 'evergreen', 'IT/기술'),
('SQL 기초 문법', 'evergreen', 'IT/기술'),
('클라우드 컴퓨팅이란', 'evergreen', 'IT/기술'),
('블록체인 기술 원리', 'evergreen', 'IT/기술'),
('메타버스 현재와 미래', 'evergreen', 'IT/기술'),
('스마트홈 구축하기', 'evergreen', 'IT/기술'),
('개인정보 보호 설정 팁', 'evergreen', 'IT/기술'),
('피그마(Figma) 사용법', 'evergreen', 'IT/기술'),
('개발자 생산성 도구', 'evergreen', 'IT/기술'),
('GPT-4 활용 사례', 'evergreen', 'IT/기술'),
('영상 편집 프로그램 추천', 'evergreen', 'IT/기술'),
('노코드(No-code) 툴 비교', 'evergreen', 'IT/기술'),
('나만의 웹사이트 만들기 (Wix, Squarespace)', 'evergreen', 'IT/기술'),
('슬랙(Slack) 효율적으로 사용하기', 'evergreen', 'IT/기술'),
('데이터 시각화 툴 비교 (태블로, Power BI)', 'evergreen', 'IT/기술'),
('사이버 보안 위협과 예방', 'evergreen', 'IT/기술'),
('VR/AR 기기 추천 및 비교', 'evergreen', 'IT/기술'),
('스마트폰 사진 잘 찍는 법', 'evergreen', 'IT/기술'),
('유튜브 쇼츠 만들기', 'evergreen', 'IT/기술'),

-- 여행
('국내 뚜벅이 여행지 추천', 'evergreen', '여행'),
('제주도 렌트카 없이 여행하기', 'evergreen', '여행'),
('부산 2박 3일 여행 코스', 'evergreen', '여행'),
('전주 한옥마을 맛집', 'evergreen', '여행'),
('강원도 오션뷰 숙소', 'evergreen', '여행'),
('혼자 가기 좋은 국내 여행지', 'evergreen', '여행'),
('애견 동반 여행지 추천', 'evergreen', '여행'),
('캠핑용품 필수 리스트', 'evergreen', '여행'),
('차박 명소 추천', 'evergreen', '여행'),
('해외여행 준비물 체크리스트', 'evergreen', '여행'),
('동남아 한달살기 비용', 'evergreen', '여행'),
('유럽 기차여행 팁', 'evergreen', '여행'),
('미국 서부 자동차 여행', 'evergreen', '여행'),
('여행 유튜버 추천', 'evergreen', '여행'),
('숨겨진 해외 휴양지', 'evergreen', '여행'),
('항공사 마일리지 사용 꿀팁', 'evergreen', '여행'),
('여행자 보험 비교 추천', 'evergreen', '여행'),
('액티비티 예약 플랫폼 비교', 'evergreen', '여행'),
('세계 3대 야경 도시', 'evergreen', '여행'),
('특이한 컨셉의 숙소 추천', 'evergreen', '여행'),
('워케이션(Workation) 명소', 'evergreen', '여행'),
('당일치기 등산 코스', 'evergreen', '여행'),

-- 건강 & 요리
('아침 공복에 좋은 음식', 'evergreen', '건강/요리'),
('저탄고지 식단 레시피', 'evergreen', '건강/요리'),
('도시락 반찬 만들기', 'evergreen', '건강/요리'),
('홈베이킹 초보 세트', 'evergreen', '건강/요리'),
('와인 안주 추천', 'evergreen', '건강/요리'),
('커피 맛있게 내리는 법', 'evergreen', '건강/요리'),
('체형별 운동 추천', 'evergreen', '건강/요리'),
('거북목 교정 스트레칭', 'evergreen', '건강/요리'),
('불면증 극복하는 방법', 'evergreen', '건강/요리'),
('정신 건강 영양제', 'evergreen', '건강/요리'),
('명상 어플 추천', 'evergreen', '건강/요리'),
('요가와 필라테스 차이', 'evergreen', '건강/요리'),
('금주 후 신체 변화', 'evergreen', '건강/요리'),
('채식주의 종류와 식단', 'evergreen', '건강/요리'),
('간헐적 단식 부작용', 'evergreen', '건강/요리'),
('글루텐프리 베이킹 레시피', 'evergreen', '건강/요리'),
('슈퍼푸드 종류와 효능', 'evergreen', '건강/요리'),
('염증 수치 낮추는 음식', 'evergreen', '건강/요리'),
('마인드풀 이팅(Mindful Eating) 방법', 'evergreen', '건강/요리'),
('콤부차 효능과 만들기', 'evergreen', '건강/요리'),
('해독 주스 레시피', 'evergreen', '건강/요리'),
('샐러드 드레싱 만들기', 'evergreen', '건강/요리'),

-- 자기계발
('외국어 빨리 배우는 법', 'evergreen', '자기계발'),
('독서모임 어플 추천', 'evergreen', '자기계발'),
('성공하는 사람들의 아침 습관', 'evergreen', '자기계발'),
('슬럼프 극복 방법', 'evergreen', '자기계발'),
('시간 관리 매트릭스', 'evergreen', '자기계발'),
('디지털 디톡스 하는 법', 'evergreen', '자기계발'),
('좋은 목소리 만드는 법', 'evergreen', '자기계발'),
('발표 잘하는 법', 'evergreen', '자기계발'),
('면접 1분 자기소개', 'evergreen', '자기계발'),
('이직 준비 로드맵', 'evergreen', '자기계발'),
('퍼스널 브랜딩 전략', 'evergreen', '자기계발'),
('블로그로 수익화하기', 'evergreen', '자기계발'),
('유튜브 시작 가이드', 'evergreen', '자기계발'),
('재능 공유 플랫폼', 'evergreen', '자기계발'),
('인생 책 추천', 'evergreen', '자기계발'),
('회고(Retrospective) 잘하는 법', 'evergreen', '자기계발'),
('논리적 사고력 키우기', 'evergreen', '자기계발'),
('비판적 사고 훈련', 'evergreen', '자기계발'),
('스터디 플래너 작성법', 'evergreen', '자기계발'),
('온라인 강의 플랫폼 비교', 'evergreen', '자기계발'),
('효과적인 재택근무 방법', 'evergreen', '자기계발'),
('독서 슬럼프 극복하기', 'evergreen', '자기계발'),
('고전 문학 추천', 'evergreen', '자기계발'),

-- 심리/라이프
('미니멀 라이프 실천법', 'evergreen', '심리/라이프'),
('플랜테리어(planterior) 식물 추천', 'evergreen', '심리/라이프'),
('반려동물 입양 전 고려사항', 'evergreen', '심리/라이프'),
('MBTI별 공부법', 'evergreen', '심리/라이프'),
('결혼 비용 절약 팁', 'evergreen', '심리/라이프'),
('중고나라 사기 피하는 법', 'evergreen', '심리/라이프'),
('도로주행 시험 팁', 'evergreen', '심리/라이프'),
('취미 부자 되는 법', 'evergreen', '심리/라이프'),
('어쿠스틱 기타 독학', 'evergreen', '심리/라이프'),
('필름카메라 입문', 'evergreen', '심리/라이프'),
('셀프 네일아트 하는 법', 'evergreen', '심리/라이프'),
('가죽 공예 배우기', 'evergreen', '심리/라이프'),
('위스키 입문 가이드', 'evergreen', '심리/라이프'),
('인간관계 정리하는 법', 'evergreen', '심리/라이프'),
('퍼스널 컬러 진단 후기', 'evergreen', '심리/라이프'),
('향수 레이어링 하는 법', 'evergreen', '심리/라이프'),
('DIY 가구 만들기', 'evergreen', '심리/라이프'),
('홈 바(Home Bar) 만들기', 'evergreen', '심리/라이프'),
('드립 커피 원두 추천', 'evergreen', '심리/라이프'),
('성격 개선 방법', 'evergreen', '심리/라이프'),
('번아웃 증후군 테스트', 'evergreen', '심리/라이프'),
('미니멀리즘 옷장 만들기', 'evergreen', '심리/라이프'),
('혼자 잘 노는 법', 'evergreen', '심리/라이프'),
('반려견 훈련 방법', 'evergreen', '심리/라이프'),
('고양이 종류별 성격', 'evergreen', '심리/라이프'),
('운전 연수 후기', 'evergreen', '심리/라이프'),
('자전거 종류 추천', 'evergreen', '심리/라이프');
