// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doiiqlqqyfxnvicvlzxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaWlxbHFxeWZ4bnZpY3ZsenhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzQ5MDIsImV4cCI6MjA2NTU1MDkwMn0.FNhB-Kjdx3TJx5BlI8pQOhWQ5oAZRvNTwtsekk9tOY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);